# Generated by Django 3.0.5 on 2022-04-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
        migrations.AddField(
            model_name='entry',
            name='text',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
